baseline_parameters:
  # total population size
  n_total: !!float 1e7
  # population proportions
  # convention is: [core, children, non-core adult]
  pop_props: [0.05, 0.45, 0.5]
  # Next generation matrix: number of infections in row i generated
  # by an infection in column j
  R_novax: [[3.0, 0.0, 0.2], [0.10, 1.0, 0.5], [0.25, 1.0, 1.5]]
  ve: 0.74
  p_severe: [0.02, 0.06, 0.02]
grid_parameters:
  n_vax_total: [0.0, !!float 2e5, !!float 1e6]
  # vaccination strategy
  vax_strategy: ["0", "1", "even"]
